CREATE TABLE tasks(
id MEDIUMINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
taskName TINYTEXT NOT NULL
);

CREATE TABLE dailytask(
id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
taskId MEDIUMINT NOT NULL,
FOREIGN KEY (taskID) REFERENCES tasks(id),
targetStartTime TIME NOT NULL,
targetEndTime TIME,
targetQuantity TINYINT NOT NULL DEFAULT 0,
targetDate DATE NOT NULL
);

CREATE TABLE dailytasktousers(
dailyTaskId BIGINT NOT NULL,
FOREIGN KEY (dailyTaskId) REFERENCES dailytask(id),
userId MEDIUMINT NOT NULL,
FOREIGN KEY (userId) REFERENCES users(id)
);